name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build project
        run: |
          mkdir -p public
          cp 1.html public/
          cp 2.html public/
          cp index.html public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
